[custom]
;设置规则标志位
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 谷歌,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=📢 谷歌,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=🔒 AI解锁,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list
;设置规则标志位

;设置分组标志位
custom_proxy_group=🔒 AI解锁`select`[]🇺🇲 美国节点
custom_proxy_group=📢 谷歌`select`[]🇺🇲 美国节点
custom_proxy_group=🇺🇲 美国节点`load-balance`(美国-家宽)`http://www.gstatic.com/generate_204`300,300,150

;设置分组标志位
enable_rule_generator=true
overwrite_original_rules=true
exclude_remarks=(看这里|剩余流量|套餐到期|重置)
;rename_node=\s{1}\|\s{1}专线@ - 一元

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
