[custom]
;设置规则标志位
ruleset=🎯 全球直连,https://raw.githubusercontent.com/IMLR/subs/main/rules/IMLR_direct.list
ruleset=⌚️ 速度测试,https://raw.githubusercontent.com/IMLR/subs/main/rules/IMLR_speedtest.list
ruleset=🎵 TikTok解锁,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/IMLR/subs/main/rules/IMLR_ban.list
ruleset=🔒 Sora解锁,https://raw.githubusercontent.com/IMLR/subs/main/rules/IMLR_sora.list
ruleset=🔒 Claude解锁,https://raw.githubusercontent.com/IMLR/subs/main/rules/IMLR_AI.list
ruleset=🔒 AI解锁,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list
ruleset=🔒 OpenRouter,https://raw.githubusercontent.com/IMLR/subs/main/rules/IMLR_OR.list
ruleset=📺 ONE解锁,https://raw.githubusercontent.com/IMLR/subs/main/rules/IMLR_one.list
ruleset=🍎 苹果TV服务,https://raw.githubusercontent.com/IMLR/subs/main/rules/IMLR_ATV.list
ruleset=🔞 JAVDB解锁,https://raw.githubusercontent.com/IMLR/subs/main/rules/IMLR_javdb.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/IMLR/subs/main/rules/IMLR_block.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/IMLR/subs/main/rules/IMLR_bing.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=📢 Play商店,https://raw.githubusercontent.com/IMLR/subs/main/rules/google_play1.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=🎮 Xbox平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Xbox.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎮 Steam平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]🚀 手动切换`[]🔯 故障转移`[]DIRECT
custom_proxy_group=🔯 故障转移`fallback`(hysteria|PLA|HK|SG|狮城)`http://www.gstatic.com/generate_204`30,30,150
custom_proxy_group=🚀 手动切换`select`.hysteria`[]🇭🇰 香港自动`[]🇺🇸 美国自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🏠 家庭宽带`[]🇭🇰 亚洲节点`[]🇪🇺 欧洲节点`[]🇦🇫 非洲节点`[]🇺🇸 北美洲节点`[]🇧🇷 南美洲节点`[]🇦🇺 大洋洲节点`[]🇦🇶 南极洲节点`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]🚀 手动切换
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择

custom_proxy_group=🔒 AI解锁`select`[]🇸🇬 狮城自动`.hysteria`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇲 美国节点`[]🇺🇸 美国自动`[]🚀 手动切换
custom_proxy_group=🔒 Claude解锁`select`[]🇸🇬 狮城家宽`[]🇸🇬 狮城自动`.hysteria`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换
custom_proxy_group=🎥 奈飞视频`select`[]🇳🇬 尼区节点`.hysteria`[]🇸🇬 狮城自动`[]🇭🇰 香港自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换
custom_proxy_group=📹 油管视频`select`[]🇳🇬 尼区节点`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换

custom_proxy_group=📺 ONE解锁`select`[]DIRECT`.hysteria`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇺🇸 美国自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🚀 手动切换
custom_proxy_group=🔞 JAVDB解锁`select`[]DIRECT`.hysteria`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换
custom_proxy_group=🔒 OpenRouter`select`.hysteria`[]🇸🇬 狮城自动`[]🇺🇸 美国自动`[]🇭🇰 香港自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🚀 节点选择`[]🚀 手动切换
custom_proxy_group=🎵 TikTok解锁`select`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 节点选择`[]🚀 手动切换`[]🏠 家庭宽带
custom_proxy_group=🔒 Sora解锁`select`[]🇺🇸 美国自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🚀 节点选择`[]🚀 手动切换

custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT`[]🚀 手动切换
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT`[]🚀 手动切换
custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT`[]🚀 手动切换
custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]DIRECT`[]🚀 手动切换



custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换
custom_proxy_group=📢 谷歌`select`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇲 美国节点`[]🇺🇸 美国自动`[]🚀 手动切换`[]🏠 家庭宽带
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换
custom_proxy_group=📢 Play商店`select`[]🇺🇸 美国自动`[]🇺🇲 美国节点
custom_proxy_group=🍎 苹果TV服务`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换
custom_proxy_group=🎮 Xbox平台`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换
custom_proxy_group=🎮 Steam平台`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🚀 手动切换

custom_proxy_group=🇸🇬 狮城自动`url-test`(新加坡)`http://www.gstatic.com/generate_204`300,250
custom_proxy_group=🇸🇬 狮城家宽`url-test`(新加坡家宽)`http://www.gstatic.com/generate_204`300,250
custom_proxy_group=🇺🇸 美国自动`url-test`(美国|纽约|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,250
custom_proxy_group=🇭🇰 香港自动`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,250
custom_proxy_group=🇹🇼 台湾自动`url-test`(台|TW)`http://www.gstatic.com/generate_204`300,250
custom_proxy_group=🇰🇷 韩国自动`url-test`(韩|KR|Korea)`http://www.gstatic.com/generate_204`300,250
custom_proxy_group=🇯🇵 日本自动`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`http://www.gstatic.com/generate_204`300,250
custom_proxy_group=🇳🇬 尼区节点`select`(尼日利亚|NG|Nigeria)
custom_proxy_group=🏠 家庭宽带`select`(家宽)


custom_proxy_group=🇸🇬 狮城节点`select`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|Hong Kong)
custom_proxy_group=🇹🇼 台湾节点`select`(台|TW)
custom_proxy_group=🇰🇷 韩国节点`select`(韩|KR|Korea)
custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)
custom_proxy_group=🇺🇲 美国节点`select`(美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)

custom_proxy_group=🇭🇰 亚洲节点`select`(🇧🇹|🇹🇱|🇨🇳|🇺🇿|🇾🇪|🇦🇲|🇮🇱|🇮🇶|🇮🇷|🇶🇦|🇮🇳|🇮🇩|🇸🇾|🇹🇼|🇰🇬|🇰🇿|🇹🇲|🇹🇷|🇹🇯|🇧🇩|🇳🇵|🇵🇸|🇵🇰|🇧🇭|🇧🇳|🇱🇰|🇸🇬|🇯🇵|🇰🇵|🇰🇭|🇬🇪|🇸🇦|🇹🇭|🇲🇴|🇰🇼|🇯🇴|🇲🇲|🇱🇦|🇵🇭|🇲🇳|🇻🇳|🇦🇿|🇦🇫|🇴🇲|🇦🇪|🇰🇷|🇭🇰|🇲🇻|🇲🇾|🇱🇧|BT|TL|CN|UZ|YE|AM|IL|IQ|IR|QA|IN|ID|SY|TW|KG|KZ|TM|TR|TJ|BD|NP|PS|PK|BH|BN|LK|SG|JP|KP|KH|GE|SA|TH|MO|KW|JO|MM|LA|PH|MN|VN|AZ|AF|OM|AE|KR|HK|MV|MY|LB)
custom_proxy_group=🇪🇺 欧洲节点`select`(🇩🇰|🇺🇦|🇷🇺|🇧🇬|🇭🇷|🇮🇸|🇱🇮|🇭🇺|🇲🇰|🇱🇺|🇸🇲|🇷🇸|🇨🇾|🇦🇽|🇦🇹|🇦🇩|🇬🇷|🇩🇪|🇮🇹|🇱🇻|🇳🇴|🇨🇿|🇲🇩|🇲🇨|🇸🇰|🇸🇮|🇬🇬|🇻🇦|🇧🇪|🇫🇷|🇫🇴|🇵🇱|🇧🇦|🇯🇪|🇮🇪|🇪🇪|🇸🇪|🇨🇭|🇧🇾|🇬🇮|🇱🇹|🇷🇴|🇫🇮|🇬🇧|🇺🇰|🇳🇱|🇵🇹|🇪🇸|🇦🇱|🇮🇲|🇲🇹|🇲🇪|DK|UA|RU|BG|HR|IS|LI|HU|MK|LU|SM|RS|CY|AX|AT|AD|GR|DE|IT|LV|NO|CZ|MD|MC|SK|SI|GG|VA|BE|FR|FO|PL|BA|JE|IE|EE|SE|CH|BY|GI|LT|RO|FI|GB|UK|NL|PT|ES|AL|IM|MT|ME)
custom_proxy_group=🇦🇫 非洲节点`select`(🇨🇫|🇺🇬|🇹🇩|🇪🇦|🇨🇻|🇬🇲|🇬🇳|🇬🇼|🇨🇬|🇨🇩|🇱🇾|🇱🇷|🇬🇭|🇬🇦|🇮🇨|🇸🇸|🇿🇦|🇧🇼|🇷🇼|🇪🇷|🇩🇯|🇨🇲|🇸🇹|🇹🇿|🇪🇬|🇪🇹|🇸🇳|🇸🇱|🇸🇨|🇹🇬|🇦🇴|🇳🇬|🇳🇪|🇧🇫|🇧🇮|🇲🇦|🇸🇿|🇲🇷|🇲🇺|🇿🇼|🇹🇦|🇷🇪|🇰🇲|🇨🇮|🇹🇳|🇸🇴|🇳🇦|🇰🇪|🇸🇩|🇲🇿|🇱🇸|🇪🇭|🇧🇯|🇿🇲|🇬🇶|🇩🇿|🇦🇨|🇲🇼|🇾🇹|🇲🇬|🇲🇱|CF|UG|TD|EA|CV|GM|GN|GW|CG|CD|LY|LR|GH|GA|IC|SS|ZA|BW|RW|ER|DJ|CM|ST|TZ|EG|ET|SN|SL|SC|TG|AO|NG|NE|BF|BI|MA|SZ|MR|MU|ZW|TA|RE|KM|CI|TN|SO|NA|KE|SD|MZ|LS|EH|BJ|ZM|GQ|DZ|AC|MW|YT|MG|ML)
custom_proxy_group=🇺🇸 北美洲节点`select`(🇧🇿|🇨🇦|🇬🇹|🇨🇺|🇨🇷|🇱🇨|🇰🇳|🇧🇱|🇻🇨|🇵🇲|🇲🇽|🇩🇲|🇩🇴|🇦🇮|🇦🇬|🇳🇮|🇧🇸|🇧🇧|🇵🇦|🇨🇼|🇰🇾|🇬🇩|🇬🇱|🇲🇫|🇵🇷|🇭🇳|🇭🇹|🇯🇲|🇹🇨|🇹🇹|🇬🇵|🇧🇲|🇺🇸|🇺🇲|🇻🇮|🇻🇬|🇧🇶|🇸🇽|🇸🇻|🇲🇸|🇦🇼|🇲🇶|BZ|CA|GT|CU|CR|LC|KN|BL|VC|PM|MX|DM|DO|AI|AG|NI|BS|BB|PA|CW|KY|GD|GL|MF|PR|HN|HT|JM|TC|TT|GP|BM|US|UM|VI|VG|BQ|SX|SV|MS|AW|MQ)
custom_proxy_group=🇧🇷 南美洲节点`select`(🇺🇾|🇪🇨|🇨🇴|🇬🇾|🇻🇪|🇵🇾|🇧🇷|🇨🇱|🇬🇫|🇧🇴|🇫🇰|🇵🇪|🇸🇷|🇦🇷|UY|EC|CO|GY|VE|PY|BR|CL|GF|BO|FK|PE|SR|AR)
custom_proxy_group=🇦🇺 大洋洲节点`select`(🇨🇵|🇬🇺|🇲🇵|🇹🇻|🇨🇽|🇰🇮|🇫🇲|🇵🇬|🇵🇼|🇨🇰|🇸🇧|🇹🇰|🇫🇯|🇳🇨|🇳🇿|🇹🇴|🇵🇫|🇦🇺|🇳🇷|🇼🇫|🇻🇺|🇵🇳|🇨🇨|🇳🇺|🇦🇸|🇼🇸|🇳🇫|🇭🇲|🇲🇭|CP|GU|MP|TV|CX|KI|FM|PG|PW|CK|SB|TK|FJ|NC|NZ|TO|PF|AU|NR|WF|VU|PN|CC|NU|AS|WS|NF|HM|MH)
custom_proxy_group=🇦🇶 南极洲节点`select`(🇬🇸|🇦🇶|🇧🇻|🇸🇯|🇹🇫|GS|AQ|BV|SJ|TF)
custom_proxy_group=⌚️ 速度测试`select`[]🚀 节点选择`.hysteria`[]🇭🇰 亚洲节点`[]🇪🇺 欧洲节点`[]🇦🇫 非洲节点`[]🇺🇸 北美洲节点`[]🇧🇷 南美洲节点`[]🇦🇺 大洋洲节点`[]🇦🇶 南极洲节点`[]DIRECT`[]🏠 家庭宽带
;设置分组标志位
enable_rule_generator=true
overwrite_original_rules=true
exclude_remarks=(看这里|剩余流量|套餐到期|重置|临时)
;rename_node=\s{1}\|\s{1}专线@ - 一元

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
